### PR TITLE
Todolist logic

### PR DESCRIPTION
**Pull request by Tripple-A**
This project focuses on building a to-do-list using vanilla javascript. Factory functions are utilized and the single responsibility principle is put into practice. Users can create new projects and add to-dos to each project. Editing todos and deleting them is possible by clicking on the todo list title. Also,deleting a project is possible. DOM Manipulation has been kept on the minimum,hence,one would have to click Project to view changes.

### CODE REVIEW

**Review by shloch — CHANGES_REQUESTED** [review]
## Hello @Tripple-A 

It hasn't been possible for me to do the review, please check again if everything is alright with configs and code. I hope it's not jus on my side. Also include live demo if possible, we can review from there in case the issue is on my PC. Here is the error i have below

Screen Shot 2020-02-01 at 1 33 13 PM

See you shortly, for another review
Thanks

**Comment by Tripple-A** [comment]
> ## Hello @Tripple-A
> It hasn't been possible for me to do the review, please check again if everything is alright with configs and code. I hope it's not jus on my side. Also include live demo if possible, we can review from there in case the issue is on my PC. Here is the error i have below
> 
> Screen Shot 2020-02-01 at 1 33 13 PM
> 
> See you shortly, for another review
> Thanks
Hi, Shey,
Video formats are not supported ,so I could not attach a live demo video but I have sent it via another means. I think the issue might have been with the local Storage,You can try again now.

**Comment by Tripple-A** [comment]
Hi, Shey,
Video formats are not supported ,so I could not attach a live demo video but I have sent it via another means. I think the issue might have been with the local Storage,You can try again now.

**Review by shloch — COMMENTED** [review]
Hello @Tripple-A 

Great job, i finally succeeded to test the app, even though there where still some warnings on the console again. But atleast, the app worked. It seems to be coming from BOOTSTRAP but not from your app.
Screen Shot 2020-02-01 at 8 35 04 PM


concerning your app alone, all your logic stands and works fluidly 
You have validated all the requirements.
Local storage works too 
Screen Shot 2020-02-01 at 8 40 06 PM


Great job, you can merge this

accomplished

## 👏👏👏👏

**Comment by shloch** [comment]
Seems this pull request is closed already ??

**Comment by Tripple-A** [comment]
Yes,it was closed and a branch was created off it in order to sort out the
issues with the live demo link being cached and main.js not being updated
but it was impossible to update the previously submitted link in the
dashboard. Find below the link to the open pull request.

https://github.com/Tripple-A/To-Do-List/pull/2

**Comment by shloch** [comment]
I have already validated ... you can merge all of them and continue......you can as well fix the issue on parent branch 🙂

**Pull request closed without merging**
